[Name1]
Meter=String
Text=#ID1name#
LeftMouseUpAction=[steam://rungameid/#ID1#]
MeterStyle=NameStyle
Hidden=1
Group=Games | G1

[Game1]
Meter=Image
MeterStyle=GameStyle
ImageName=C:\Program Files (x86)\Steam/appcache/librarycache\#ID1#\icon.jpg
LeftMouseUpAction=[steam://rungameid/#ID1#]
Hidden=1
Group=Games | G1

[Gap1]
Meter=Image
MeterStyle=GapStyle

[Name2]
Meter=String
Text=#ID2name#
LeftMouseUpAction=[steam://rungameid/#ID2#]
MeterStyle=NameStyle
Hidden=1
Group=Games | G2

[Game2]
Meter=Image
MeterStyle=GameStyle
ImageName=C:\Program Files (x86)\Steam/appcache/librarycache\#ID2#\icon.jpg
LeftMouseUpAction=[steam://rungameid/#ID2#]
Hidden=1
Group=Games | G2

[Gap2]
Meter=Image
MeterStyle=GapStyle

[Name3]
Meter=String
Text=#ID3name#
LeftMouseUpAction=[steam://rungameid/#ID3#]
MeterStyle=NameStyle
Hidden=1
Group=Games | G3

[Game3]
Meter=Image
MeterStyle=GameStyle
ImageName=C:\Program Files (x86)\Steam/appcache/librarycache\#ID3#\icon.jpg
LeftMouseUpAction=[steam://rungameid/#ID3#]
Hidden=1
Group=Games | G3

[Gap3]
Meter=Image
MeterStyle=GapStyle

